# Generated by Django 4.1.5 on 2023-01-24 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=200)),
                ('data_content', models.CharField(max_length=200)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.computer')),
            ],
        ),
    ]
