# Generated by Django 4.1.5 on 2023-01-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_data_pub_date_alter_computer_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
    ]
