# Generated by Django 4.1.5 on 2023-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_data_is_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
