# Generated by Django 4.1.5 on 2023-01-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='staged',
            field=models.BooleanField(default=True),
        ),
    ]
